### ISSUE TITLE
Tag mod as 1.20.6-compatible

### ISSUE THREAD

**Issue by anoomolu** [SFort/MC-oldregen#2]
Hiya. 

I wasn't able to find Good Ol' Regen through Prism Launcher on 1.20.6 so I checked CF, found that it's not tagged as compatible despite seeming to work fine on that version. You might wanna tag it as compatible so that other users can find it through their mod launcher of choice.

**Comment by SFort** [comment]
Thanks!
i forgot about 1.20.6 compleatly, will update as soon as curseforge stops being under load and actually loads the site.
